name: CMake

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install deps 
      run: sudo apt update
       && sudo apt install libboost-dev-all
       && sudo apt install Doxygen
    
    - name: Prepare build
      run: cd Executor && mkdir build && cd build

    - name: Configure CMake
      run: cmake ..
      
    - name: Build the doc
      run: make docs
        
      
