name: CMake

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  BUILD_TYPE: Release

jobs:
  Configure_env:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
            submodules: recursive

    - name: Install deps 
      run: sudo apt update
       && sudo apt install libboost-all-dev 
       && sudo apt install doxygen
       && sudo apt install graphviz

    - name: Configure CMake
      run: cd Executor && mkdir build && cd build && cmake ..
      
  Build_doc:
    runs-on: ubuntu-latest
    needs: Configure_env
    steps:
      
    - name: Build the doc
      run: cd Executor && cd build && make docs
      
  Publish_doc:
    runs-on: ubuntu-latest
    needs: Build_doc
    
    steps:
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages # The branch the action should deploy to.
        FOLDER: Executor/build/executor/docs/html # The folder the action should deploy.
        
      
