name: CMake

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: debian-latest

    steps:
    - uses: actions/checkout@v2

    - name: Configure CMake
      run: apt update
       && apt install libboost-dev-all
       && apt install Doxygen
    
    - name: Prepare build
      run: cd Executor && mkdir build && cd build

    - name: Configure CMake
      run: cmake ..
      
    - name: Build the doc
      run: make docs
        
      
